src/tsconf.c: Mark a set-but-unused variable with UNUSED
It fixes this error:

tsconf.c: In function ‘tsconf_store_scanline_border_supinf_izqder’:
tsconf.c:1459:18: error: variable ‘alto’ set but not used [-Werror=unused-but-set-variable]
  int ancho_linea,alto;
                  ^~~~

Signed-off-by: Böszörményi Zoltán <zboszor@pr.hu>